"""Initial migration for event store

Revision ID: 001_initial_event_store
Revises: 
Create Date: 2025-08-06 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_event_store'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create workflow_events table
    op.create_table('workflow_events',
        sa.Column('event_id', sa.String(length=36), nullable=False),
        sa.Column('workflow_id', sa.String(length=36), nullable=False),
        sa.Column('execution_id', sa.String(length=36), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('event_version', sa.Integer(), nullable=True, default=1),
        sa.Column('timestamp', postgresql.TIMESTAMPTZ(), nullable=False),
        sa.Column('actor', sa.String(length=255), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, default={}),
        sa.Column('sequence_number', sa.BigInteger(), autoincrement=True, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMPTZ(), server_default=sa.text('NOW()'), nullable=True),
        sa.PrimaryKeyConstraint('event_id'),
        sa.UniqueConstraint('sequence_number')
    )
    
    # Create indexes for workflow_events
    op.create_index('idx_workflow_events_workflow', 'workflow_events', ['workflow_id', 'sequence_number'])
    op.create_index('idx_workflow_events_execution', 'workflow_events', ['execution_id', 'sequence_number'])
    op.create_index('idx_workflow_events_type', 'workflow_events', ['event_type', 'timestamp'])
    op.create_index('idx_workflow_events_created', 'workflow_events', ['created_at'])
    
    # Create execution_snapshots table
    op.create_table('execution_snapshots',
        sa.Column('snapshot_id', sa.String(length=36), nullable=False),
        sa.Column('execution_id', sa.String(length=36), nullable=False),
        sa.Column('workflow_id', sa.String(length=36), nullable=False),
        sa.Column('sequence_number', sa.BigInteger(), nullable=False),
        sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMPTZ(), server_default=sa.text('NOW()'), nullable=True),
        sa.PrimaryKeyConstraint('snapshot_id'),
        sa.UniqueConstraint('execution_id', 'sequence_number', name='uq_execution_sequence')
    )
    
    # Create index for execution_snapshots
    op.create_index('idx_snapshots_execution', 'execution_snapshots', ['execution_id', 'sequence_number'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop execution_snapshots table
    op.drop_index('idx_snapshots_execution', table_name='execution_snapshots')
    op.drop_table('execution_snapshots')
    
    # Drop workflow_events table
    op.drop_index('idx_workflow_events_created', table_name='workflow_events')
    op.drop_index('idx_workflow_events_type', table_name='workflow_events')
    op.drop_index('idx_workflow_events_execution', table_name='workflow_events')
    op.drop_index('idx_workflow_events_workflow', table_name='workflow_events')
    op.drop_table('workflow_events')
    
    # ### end Alembic commands ###
